source 'https://binrepo.target.com/artifactory/api/gems/basetgt-gems/'
source 'https://binrepo.target.com/artifactory/api/gems/basetgt-gem-local/'

gem 'test-kitchen', '1.7.3'
gem 'kitchen-vagrant'
gem 'kitchen-openstack'
gem 'rake'
gem 'rspec'
gem 'rubocop'
gem 'foodcritic'
gem 'berkshelf'
gem 'chef'
gem 'chefspec'
gem 'rack', '~> 1.6.4'
