name             'ethercalc'
maintainer       'Target Corp'
maintainer_email 'david.fredkove@target.com'
license          'All rights reserved'
description      'Docker compose ethercalc instance with redis'
long_description 'Docker compose ethercalc instance with redis'
version          '0.1.0'

depends 'lvm'
depends 'selinux'
